- name: install php
  apt: name=php update_cache=yes state=latest

- name: install php modules
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - php-curl
   - php-gd
   - php-ssh2
   - php-mbstring
   - php-xml
   - php-xmlrpc
   - php-soap
   - php-intl
   - php-zip
