# MySQL installation and configuration

- name: install mysql packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'mysql-server', 'php-mysql', 'python3-pymysql', 'python3-mysqldb' ]

- name: start mysql server
  systemd: name=mysql state=started enabled=yes

- name: create mysql database
  mysql_db: 
    login_user: root
    login_password: root 
    name: "{{ wp_mysql_db }}"
    state: present
  become: yes

- name: create mysql user
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: "{{ wp_mysql_db }}.*:ALL"
  become: yes 
